fragment OrderFields on Order {
  id
  orderNumber
  createdAt
  lineItems {
    id
    name(locale: $locale)
    productSlug(locale: $locale)
    quantity
    price {
      value {
        ...MoneyFields
      }
      discounted {
        value {
          ...MoneyFields
        }
      }
    }
    totalPrice {
      ...MoneyFields
    }
    variant {
      sku
      images {
        url
      }
      attributesRaw {
        name
        value
        attributeDefinition {
          type {
            name
          }
          name
          label(locale:$locale)
        }
      }
    }
  }
  returnInfo {
    items {
      ... on LineItemReturnItem {
        lineItemId
        quantity
      }
      type
    }
  }
  totalPrice {
    ...MoneyFields
  }
  shippingInfo {
    shippingMethod {
      name
      localizedDescription(locale:$locale)
    }
    price {
      ...MoneyFields
    }
  }
  taxedPrice {
    totalGross {
      ...MoneyFields
    }
    totalNet {
      ...MoneyFields
    }
  }
  discountCodes {
    discountCode {
      id
      code
      name(locale: $locale)
    }
  }
  shippingAddress {
    ...AddressFields
  }
  billingAddress {
    ...AddressFields
  }
  paymentInfo {
    payments {
      paymentStatus {
        interfaceCode
      }
    }
  }
}