#import "./DisplayableMoney.gql"

fragment UpdatableCartInfo on Cart {
  id
  version
  totalPrice {
    ...DisplayableMoney
  }
  shippingInfo {
    price {
      ...DisplayableMoney
    }
  }
  taxedPrice {
    totalGross {
      ...DisplayableMoney
    }
    totalNet {
      ...DisplayableMoney
    }
  }
  lineItems {
    id
    quantity
    price {
      value {
        ...DisplayableMoney
      }
      discounted {
        value {
          ...DisplayableMoney
        }
      }
    }
    totalPrice {
      ...DisplayableMoney
    }
  }
}

# import does not work https://github.com/apollographql/graphql-tag/issues/159
fragment DisplayableMoney on Money {
  centAmount
  currencyCode
  fractionDigits
}
