query navigationalCategories($locale: Locale!) {
  categories(limit: 10, where: "parent is not defined", sort: "orderHint asc") {
    total
    results {
      ...printCategory
      children {
        ...printCategory
      }
    }
  }
}

fragment printCategory on Category {
  id
  externalId
  name(locale: $locale)
  slug(locale: $locale)
}